# Generated by Django 5.2.7 on 2026-03-11 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_on', models.BooleanField(default=False)),
                ('text_font', models.CharField(default='Arial', max_length=20)),
                ('theme_name', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('solarized', 'Solarized')], default='light', max_length=20)),
                ('theme_background', models.CharField(max_length=7)),
                ('theme_text_color', models.CharField(max_length=7)),
                ('theme_accent_color', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(null=True)),
                ('grade', models.CharField(blank=True, choices=[('9', 'Freshman'), ('10', 'Sophmore'), ('11', 'Junior'), ('12', 'Senior'), ('NA', 'Other')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
