# Generated by Django 5.2.7 on 2026-05-06 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuoMobileAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('duo_username', models.CharField(blank=True, help_text="Defaults to the user's email, then username.", max_length=150)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duo_mfa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempOTP_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('is_tempOTP_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='My PC', max_length=80)),
                ('desktop_url', models.URLField(blank=True)),
                ('bridge_status_host', models.CharField(blank=True, max_length=255)),
                ('bridge_status_port', models.PositiveIntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('access_password_1_hash', models.CharField(blank=True, max_length=128)),
                ('access_password_2_hash', models.CharField(blank=True, max_length=128)),
                ('access_password_3_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
