# Generated by Django 5.2.7 on 2026-05-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_duomobileauth_mfa_usercomputer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DuoMobileAuth",
        ),
    ]
