# Generated by Django 5.2.7 on 2026-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_delete_duomobileauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercomputer",
            name="guac_password_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="usercomputer",
            name="guac_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="usercomputer",
            name="guac_uses_account_password",
            field=models.BooleanField(default=True),
        ),
    ]
