# Generated by Django 5.2.7 on 2026-05-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_usercomputer_guac_password_encrypted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercomputer",
            name="access_password_1_hash",
        ),
        migrations.RemoveField(
            model_name="usercomputer",
            name="access_password_2_hash",
        ),
        migrations.RemoveField(
            model_name="usercomputer",
            name="access_password_3_hash",
        ),
    ]
