# Generated by Django 6.0.5 on 2026-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_usercomputer_access_password_1_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfa',
            name='mfa_frequency_minutes',
            field=models.PositiveIntegerField(default=90, help_text='How often MFA is required for PC access (in minutes). Default is 90 minutes.'),
        ),
    ]
