# Generated by Django 6.0.5 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_mfa_mfa_frequency_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="pc_totp_required",
            field=models.BooleanField(
                default=True,
                help_text="Require a TOTP or other configured MFA method before opening remote PC access.",
            ),
        ),
    ]
