# Generated by Django 6.0.5 on 2026-05-20 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('refresh_token', models.TextField(blank=True)),
                ('last_history_ID', models.BigIntegerField(blank=True, null=True)),
                ('token_JSON', models.TextField(blank=True, null=True)),
                ('last_use', models.DateTimeField(blank=True, null=True)),
                ('organize_inbox', models.BooleanField(default=False)),
                ('use_advanced_settings', models.BinaryField()),
                ('track_emails', models.BinaryField()),
                ('random_sorting', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
