# Generated by Django 5.2.7 on 2026-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Source', models.CharField(max_length=50)),
            ],
        ),
    ]
