# Generated by Django 6.0.5 on 2026-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='aspect_ratio',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='source',
            field=models.CharField(blank=True, choices=[('Grandparents', 'Grandparents'), ('Grandpa', 'Grandpa'), ('Grandma', 'Grandma'), ('Uncle/Monica', 'Uncle/Monica'), ('Uncle', 'Uncle'), ('Monica', 'Monica'), ('Us', 'Us'), ('Auntie', 'Auntie'), ('Frank', 'Frank'), ('Torrent', 'Torrent'), ('N/A', 'N/A')], default='', max_length=50),
        ),
    ]
