# Generated by Django 6.0.5 on 2026-06-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_movie_aspect_ratio_alter_movie_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='still_have_it',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='music',
            name='still_have_it',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tvepisode',
            name='still_have_it',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='still_have_it',
            field=models.BooleanField(default=True),
        ),
    ]
