# Generated by Django 6.0.5 on 2026-09-20 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_movie_still_have_it_music_still_have_it_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('authors', models.CharField(blank=True, default='', help_text='Use a semicolon between multiple authors.', max_length=500)),
                ('contributors', models.CharField(blank=True, default='', help_text='Illustrators, editors, translators, narrators, and so on.', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('series_name', models.CharField(blank=True, default='', max_length=255)),
                ('series_number', models.CharField(blank=True, default='', max_length=30)),
                ('volume_number', models.CharField(blank=True, default='', max_length=30)),
                ('edition', models.CharField(blank=True, default='', max_length=100)),
                ('printing', models.CharField(blank=True, default='', max_length=100)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('imprint', models.CharField(blank=True, default='', max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('original_publication_date', models.DateField(blank=True, null=True)),
                ('copyright_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('original_language', models.CharField(blank=True, default='', max_length=100)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn_10', models.CharField(blank=True, default='', max_length=20)),
                ('isbn_13', models.CharField(blank=True, default='', max_length=20)),
                ('oclc_number', models.CharField(blank=True, default='', max_length=30)),
                ('library_of_congress_number', models.CharField(blank=True, default='', max_length=50)),
                ('open_library_id', models.CharField(blank=True, default='', max_length=50)),
                ('goodreads_id', models.CharField(blank=True, default='', max_length=50)),
                ('binding', models.CharField(blank=True, choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('leather_bound', 'Leather-bound'), ('cloth_bound', 'Cloth-bound'), ('perfect_bound', 'Perfect-bound'), ('saddle_stitched', 'Saddle-stitched'), ('spiral_or_wire_bound', 'Spiral or wire-bound'), ('comb_bound', 'Comb-bound'), ('board_book', 'Board book'), ('loose_leaf', 'Loose-leaf'), ('boxed_set', 'Boxed set'), ('ebook', 'eBook'), ('audiobook', 'Audiobook'), ('other', 'Other')], default='', max_length=25)),
                ('cover_material', models.CharField(blank=True, default='', help_text='For example: paper, cloth, genuine leather, or faux leather.', max_length=100)),
                ('dimensions', models.CharField(blank=True, default='', help_text='For example: 8.5 x 11 in.', max_length=100)),
                ('weight_oz', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('genres', models.CharField(blank=True, default='', max_length=500)),
                ('subjects', models.CharField(blank=True, default='', max_length=1000)),
                ('is_illustrated', models.BooleanField(default=False)),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'edition', 'publication_date'],
            },
        ),
        migrations.CreateModel(
            name='BookContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('self', 'Me'), ('family', 'Family member'), ('friend', 'Friend'), ('organization', 'Organization'), ('other', 'Other')], default='family', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Optionally link this person to a website account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('collection_status', models.CharField(choices=[('in_collection', 'In our collection'), ('lent_out', 'Lent out'), ('gifted', 'Given as a gift'), ('sold', 'Sold'), ('donated', 'Donated'), ('lost', 'Lost'), ('discarded', 'Discarded')], default='in_collection', max_length=20)),
                ('current_location', models.CharField(blank=True, default='', help_text="For example: home office, attic, or Jane's house.", max_length=255)),
                ('shelf_location', models.CharField(blank=True, default='', max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like new'), ('very_good', 'Very good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='', max_length=20)),
                ('has_dust_jacket', models.BooleanField(default=False)),
                ('dust_jacket_condition', models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like new'), ('very_good', 'Very good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='', max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_by', models.CharField(blank=True, default='', max_length=255)),
                ('inscription', models.TextField(blank=True, default='')),
                ('personalized_to', models.CharField(blank=True, default='', max_length=255)),
                ('acquisition_method', models.CharField(blank=True, choices=[('purchased', 'Purchased'), ('gift_received', 'Gift received'), ('inherited', 'Inherited'), ('borrowed', 'Borrowed'), ('donated_to_us', 'Donated to us'), ('found', 'Found'), ('other', 'Other')], default='', max_length=20)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquired_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_acquired_from_them', to='APIs.bookcontact')),
                ('current_holder', models.ForeignKey(blank=True, help_text='The person who currently has this copy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_currently_holding', to='APIs.bookcontact')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='APIs.books')),
            ],
            options={
                'ordering': ['book__title', 'inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='BookTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('loan', 'Loaned'), ('return', 'Returned'), ('gift', 'Given as a gift'), ('sale', 'Sold'), ('donation', 'Donated'), ('transfer', 'Transferred')], max_length=20)),
                ('transferred_on', models.DateField()),
                ('due_back_on', models.DateField(blank=True, null=True)),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='APIs.bookcopy')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_transfers_sent', to='APIs.bookcontact')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_transfers_received', to='APIs.bookcontact')),
            ],
            options={
                'ordering': ['-transferred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BookReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('reading', 'Reading'), ('read', 'Read'), ('did_not_finish', 'Did not finish'), ('reference', 'Reference only')], default='not_started', max_length=20)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='APIs.bookcontact')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='APIs.books')),
            ],
            options={
                'ordering': ['reader__name', 'book__title'],
                'constraints': [models.UniqueConstraint(fields=('book', 'reader'), name='unique_book_reading_per_reader'), models.CheckConstraint(condition=models.Q(('rating__isnull', True), ('rating__lte', 5), _connector='OR'), name='book_reading_rating_at_most_five')],
            },
        ),
    ]
