# Generated by Django 5.2.7 on 2026-03-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('formula', models.CharField(max_length=30)),
                ('molar_mass', models.FloatField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
