# Generated by Django 5.2.7 on 2026-03-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='particle',
            name='common_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
