# Generated by Django 6.0.5 on 2026-05-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_particle_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='particle',
            name='common_name_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='particle',
            name='common_name_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='particle',
            name='common_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='particle',
            name='formula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='particle',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
