# Generated by Django 5.2.7 on 2026-05-15 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('duration_s', models.FloatField(default=5.0)),
                ('FPS', models.FloatField(default=30)),
                ('quality', models.CharField(default='preview')),
                ('world', models.CharField(default='arena')),
                ('behavior', models.CharField(default='wander')),
                ('seed', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4294967295)])),
                ('arena_size', models.FloatField(default=10.0)),
                ('data_path', models.CharField(default='m:/C VSCode/.vscode/Fly/proofread_connections_783.feather')),
                ('max_saved_frames', models.IntegerField(default=500)),
                ('cpu_max_percent', models.FloatField(blank=True, null=True)),
                ('cpu_avg_percent', models.FloatField(blank=True, null=True)),
                ('cpu_min_percent', models.FloatField(blank=True, null=True)),
                ('gpu_max_percent', models.FloatField(blank=True, null=True)),
                ('gpu_avg_percent', models.FloatField(blank=True, null=True)),
                ('gpu_min_percent', models.FloatField(blank=True, null=True)),
                ('vram_max_gb', models.FloatField(blank=True, null=True)),
                ('vram_avg_gb', models.FloatField(blank=True, null=True)),
                ('vram_min_gb', models.FloatField(blank=True, null=True)),
                ('ram_max_gb', models.FloatField(blank=True, null=True)),
                ('ram_avg_gb', models.FloatField(blank=True, null=True)),
                ('ram_min_gb', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
